version: 2.1
orbs:
  heroku: circleci/heroku@2.0
jobs:
  testing:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run: sudo apt-get install libssl1.1
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Test the app
          command: npm test
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git
      - run:
          name: Check deployment status
          command: |
            heroku ps --app $HEROKU_APP_NAME
workflows:
  heroku_deploy:
    jobs:
      - testing
      - deploy:
          requires:
            - testing
